language:
  - java
  - scala
  - python
  - groovy

os:
  - windows
  - linux

jdk:
  - oraclejdk8

scala:
  - 2.11.8

python:
  - 2.7.12

groovy:
  - 2.3.11

before_install: sudo echo "MAVEN_OPTS='-Xmx2048m -Xms1024m -Dorg.slf4j.simpleLogger.defaultLogLevel=error'" > ~/.mavenrc

script:
  - mvn clean install -B && mvn clean -B

env:
  global:
    - MAVEN_OPTS: "-Xmx2048m -Xms1024m -Dorg.slf4j.simpleLogger.defaultLogLevel=error"

sudo: required

cache:
  directories:
      - $HOME/.m2